# Generated by Django 4.0.4 on 2022-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='handphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=20)),
                ('design', models.CharField(max_length=20)),
                ('storage', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('peforma', models.CharField(max_length=20)),
            ],
        ),
    ]
