# Generated by Django 4.0.4 on 2022-04-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AHP', '0002_peforma_alter_handphone_peforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='handphone',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AHP.design'),
        ),
    ]
