# Generated by Django 4.0.4 on 2022-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHP', '0004_alter_handphone_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='kepentingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
    ]
