# Generated by Django 4.0.4 on 2022-04-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AHP', '0006_handphone_kepentingan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handphone',
            name='kepentingan',
        ),
    ]
