# Generated by Django 4.0.4 on 2022-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHP', '0009_delete_kepentingan_delete_nilai_penting'),
    ]

    operations = [
        migrations.CreateModel(
            name='kepentingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('peforma', models.IntegerField()),
            ],
        ),
    ]
